### ISSUE TITLE
Caching with different states

### ISSUE THREAD

**Issue by ogezue** [buzzfeed/mattress#34]
I have recognized that a page often ends loading with a different state. I printing the line 
```let state = webView.stringByEvaluatingJavaScriptFromString("document.readyState")```
to the console. Sometimes it finishes with "interactive" and sometimes with "completed" when loading the same url.  Should the caching process then be repeated?

I tried to cache different pages consequently by calling. 
```
cachePage(SiteA)
cachePage(SiteB)
cachePage(SiteC)
```
Is it possible that I have to wait until the former caching process has been completed? What I'm trying to achieve is that my apps caches certain pages after initialization to present them as fast as possible when the user visits them.

Another question: Does the caching mechanism needs an instance of a webView in my class or can it cache independently, so that I can put cachePage in it's own model class?

```
    func cachePage(url: NSURL) {
        log.info("Caching page \(url.absoluteString)")
        if let cache = NSURLCache.sharedURLCache() as? Mattress.URLCache
        {
            cache.diskCacheURL(url, loadedHandler: { (webView) -> (Bool) in
                    let state = webView.stringByEvaluatingJavaScriptFromString("document.readyState")
                    log.verbose("state: \(state)")
                    return state == "complete"
                }, completeHandler: { () -> Void in
                    log.info("Finished caching \(url.absoluteString)")
                }, failureHandler: { (error) -> Void in
                    log.error("Error caching: \(error.localizedDescription)")
            })
        }
    }
```

**Comment by dmauro** [comment]
Hey, thanks for giving Mattress a shot!

The document's readyState being different sometimes is to be expected. UIWebView's delegate method for when it's finished loading gets called usually several times, and we don't really know when it's going to get called. That's why we let you decide when you're all done loading, so we can be as hands off as possible about the process.

It looks like you're waiting for the "complete" readyState, but you could actually see that handler get called zero to many times *before* it's called when "complete". That's to be expected and doesn't mean anything went wrong or that you need to re-run the caching process. You'd only want to consider re-running if the failure handler is called, but keep in mind that the failureHandler is called when the webView delegate's failure method is called, which could just be due to a single request failing, rather than what you might consider a catastrophic failure.

Since you're just trying to get pages to load a bit faster, the implementation above looks good, if you're not worried about handling a catastrophic failure state. That's actually very similar to what we're doing in our News app, except we will actually return true regardless of readyState if the user is not on WiFi. 

Since your'e trying to speed up downloads rather than just make them offline, you'll need to use a not-so-well documented features:
`Mattress.shouldRetrieveFromMattressCacheByDefault` and the request key `MattressAvoidCacheRetreiveOnlineRequestPropertyKey`.

The former is a bool that determines if we should look into the Mattress cache for files, even when we're online. And the latter is a key for a request header property where you can specify that you want to bypass looking in the MattressCache. Be careful with using this though because if you have `shouldRetrieveFromMattressCacheByDefault` turned on, it will load any available requests from the cache, regardless of how old they are. You could end up getting some very stale data. This is probably fine for things like CSS and JS, which often use filename invalidation already anyways, but for downloading an HTML file for example you might not want to use it.

We use this feature in the News app like so:
`Mattress.shouldRetrieveFromMattressCacheByDefault` is set to true. And in our web view controller where we're loading the request for a web page, we do this:
```
    func startLoadingURL(url: NSURL) {
        let request = NSMutableURLRequest(URL: url)
        NSURLProtocol.setProperty(true, forKey: MattressAvoidCacheRetreiveOnlineRequestPropertyKey, inRequest: request)
        webView.loadRequest(request)
    }
```

What that does for us is makes sure the initial request (most likely the HTML) will not load from cache unless we're offline, so it will download fresh content, then subsequence requests that page causes *will* load from the Mattress cache so they'll come up instantly. It results in *much* faster page loads, but also ensures your HTML is up to date.

Sorry, I know that's probably a much longer answer than you were looking for, but Mattress is primary designed for making offline consumption easier, and this speedier while online loading approach is something that is a bit harder to offer for users. Something for us to work on though!

For your second question: you don't need to supply a WebView. Every time you call diskCacheURL, a webView gets created by Mattress and is used to do the loading behind the scenes. In the News app our calls to diskCacheURL are in an NSOperation subclass that knows nothing about UIWebViews. :)

**Comment by dmauro** [comment]
And I realized I didn't really answer one of your questions:
You do not have to wait for one of your offline calls to complete before doing another. Behind the scenes Mattress will create a new webView for each of them (so be careful not to create too many!). In our News app we have a queue system built that ensure we only ever run 4 of these at once. That's kind of an arbitrary number we came up with that seemed fair, but we're only running it during the backgroundFetch process.

**Comment by ogezue** [comment]
Hi David - thank you very much for your detailed answer! This really helped me a lot. I now ended up with this class:
```
class WebViewCache {

    
    static func cachePage(urlAsString: String){
        
        let url  = NSURL(string: urlAsString)
        if let url = url{
            cachePage(url, cachingAttempt: 1)
        }
    }
    
    
    static func cachePage(url: NSURL, cachingAttempt: Int) {
        log.info("Caching page \(url.absoluteString)")
        if let cache = NSURLCache.sharedURLCache() as? Mattress.URLCache
        {
            cache.diskCacheURL(url, loadedHandler: { (webView) -> (Bool) in
                    let state = webView.stringByEvaluatingJavaScriptFromString("document.readyState")
                    return state == "complete"
                }, completeHandler: { () -> Void in
                    log.info("Finished caching \(url.absoluteString)")
                }, failureHandler: { (error) -> Void in
                    log.error("Error caching: \(error.localizedDescription)")
                    if cachingAttempt < 3 {
                        log.warning("Retrying caching...")
                        self.cachePage(url, cachingAttempt: cachingAttempt+1)
                    }
            })
        }
    }
    
    
    static func setupCaching(){
        
        let kB = 1024
        let MB = 1024 * kB
        let GB = 1024 * MB
        
        let isOfflineHandler: (() -> Bool) = {
            let isOffline = !ReachabilityHelper.sharedInstance.isOnline
            return isOffline
        }
        
        let urlCache = Mattress.URLCache(memoryCapacity: 20 * MB, diskCapacity: 20 * MB, diskPath: nil,
            mattressDiskCapacity: 1 * GB, mattressDiskPath: nil, mattressSearchPathDirectory: .DocumentDirectory,
            isOfflineHandler: isOfflineHandler)
        
        NSURLCache.setSharedURLCache(urlCache)
        
        Mattress.shouldRetrieveFromMattressCacheByDefault = true
        
    }
}
```

My use case is a conference app where the wifi sometimes is really bad. You are logged into but your request fail because your session has ended and you first have to make the web portal happy. Then there are hundreds of users and the wifi collapses.

My idea ist that after the app is started for the first time I cache alle web pages in my app (defined content from the cms). I think this is now covered with the code above. By the way: When you check the online-state: Do you try to check the reachability of a certain resource?

Another idea I have is to deploy a basic cache with the app-store build, so the users never get no data if they are offline. Do you also have some input for me here?

**Comment by dmauro** [comment]
A suggestion for your failure handler: Consider not failing if the loaded handler has already been called, because in that case, it could just be that a non-critical resource failed to download.

I believe we test our reachability against buzzfeed.com; If your'e just looking for a domain to use, perhaps google.com would be good.

On your third point, are you talking about bundling in the web content with your app so users would get it even if they have never been online with the app? We don't support that, and it might be a bit out of scope, but feel free to make a feature request in a separate issue! :)

**Comment by ogezue** [comment]
So you mean the better approach would be this?

```
    static func cachePage(url: NSURL, cachingAttempt: Int) {
        log.info("Caching page \(url.absoluteString)")
        if let cache = NSURLCache.sharedURLCache() as? Mattress.URLCache
        {
            var completed = false
            
            cache.diskCacheURL(url, loadedHandler: { (webView) -> (Bool) in
                
                let state = webView.stringByEvaluatingJavaScriptFromString("document.readyState")
                completed = (state == "complete")
                
                return completed
            
                }, completeHandler: { () -> Void in
                    log.info("Finished caching \(url.absoluteString)")
                }, failureHandler: { (error) -> Void in
                    log.error("Error caching: \(error.localizedDescription)")
                    if (cachingAttempt < 3 && completed == false)  {
                        log.warning("Retrying caching...")
                        self.cachePage(url, cachingAttempt: cachingAttempt+1)
                    }
            })
        }
    }
```

**Comment by dmauro** [comment]
Something more like this in your completion block might be the way to go:
```
                let state = webView.stringByEvaluatingJavaScriptFromString("document.readyState")
                completed = true
                return state == "complete"
```

It all depends on how vigilant or lenient you want to be about request failures though. This is a little more lenient, so you won't be trying over and over which could be a big battery drain.

**Comment by ogezue** [comment]
thanks for your input!
