### ISSUE TITLE
FeatureRequest: Ship cached websites with app store build

### ISSUE THREAD

**Issue by ogezue** [buzzfeed/mattress#36]
I'm creating a conference app with an integration of some websites for venue, sponsors etc. This pages do not change quite often and it would be great to ship them cached with the app store build.

Some users start the app at the conference center for the first time where wifi conditions are sometimes very poor. Instead of showing a blank page the users should see at least "something".

It would be great if mattress could support this. What I currently would do is caching the websites within the simulator, cache the contents of the required pages and zip the mattress folder afterwards to ship  it with the app (Currently there is a bug, see https://github.com/buzzfeed/mattress/issues/33). 

Is there something that can be solved by mattress to improve this process? For example that mattress could create the zip-file and present a mail dialog to bring the file to the devs machine? Or to update the cache automatically before creating the app store build? 
Will the cache be working on other devices?

**Comment by evermeer** [comment]
With the above strategy I have had an app rejected by Apple once. Apple does not want you to copy out data from you app bundle to the document folder. They said that the app used to much document space on startup where the data was generated from the app itself.

How this could work (with a minor fix to this library):
- Add a PreCache folder inside your app with content that you will distribute with your app.
- When checking if a cache item exists, first check the documents Cache folder, if it's not there, then check the PreCache folder and return that.
Other things to take into account:
- when writing to the cache, first check if it exists in the PreCache folder. If it exist there, then always write it to the Cache folder so that you always will have the latest version. Even if the caching policy is none. 
This is the way I have set it up for https://github.com/evermeer/EVURLCache

**Comment by ogezue** [comment]
thank you very much for this tips!
